### ISSUE TITLE
Unable to activate package as json-rpc-0.0.1 is unavailable

### ISSUE THREAD

**Issue by JBKahn** [proofit404/anaconda-mode#111]
I'm getting this using spacemacs:
```
Warning (emacs): Unable to activate package `anaconda-mode'.
Required package `json-rpc-0.0.1' is unavailable
Warning (emacs): Unable to activate package `anaconda-mode'.
Required package `json-rpc-0.0.1' is unavailable
Error (use-package): helm :config: Invalid function: add-function
```
I tried manually pip installing the package and reinstalling but that didn't fix it.
I'm wondering if you've seen this error before or know how I might solve it?

**Comment by proofit404** [comment]
This is really strange so far. `anaconda-mode` doesn't use `json-rpc` package any more. But it looks similar to last comments in the #109

**Comment by proofit404** [comment]
May it be `use-package` issue?

**Comment by JBKahn** [comment]
What do you mean? I'm very very very new to Emacs.

**Comment by proofit404** [comment]
@JBKahn actually anaconda-mode composed from two packages. Client side written in Emacs lisp and server side written in python. You errors belongs to Emacs package. As far as I know Spacemacs uses `use-package` (DSL around `package.el` the Emacs Lisp package manager) which is itself another package :smile: Unfortunately `anaconda-mode` is really tricky inside due to its nature. I hope it is easy for regular users on the other hand.

@syl20bnr @jwiegley Since I doesn't use Spacemacs and `use-package` may be you guys can give me some points on this problem.

**Comment by JBKahn** [comment]
Oh I fixed this problem, I upgraded emacs the other day and forgot to blow away my old `~/.emacs.d/elpa`. and ran emacs again to reinstall all my packages.

But right now I'm getting `File mode specification error  (error "required feature 'f' was not provided")` when I open up a python file to try to use it. I know if might not be your package in particular but do you happen to know anything about this?

**Comment by proofit404** [comment]
Looks like `f` package isn't in your `load-path` (not installed).

**Comment by JBKahn** [comment]
I tried adding it in and got a bit confused I'm going to try to fix this over the weekend and hopefully I'll have no more issues :)

**Comment by proofit404** [comment]
You can continue asking questions here or mail me directly. No problem with that.
