### ISSUE TITLE
Highlight the line containing the reference when finding references

### ISSUE THREAD

**Issue by vskr** [proofit404/anaconda-mode#143]
When finding references using M-r, it opens another buffer with all the refereces, and when navigating through all the references, buffer[1] opens the file containing the reference.

Would be great if buffer[1] also highlights the line containing the reference. (e.g. M-x find-grep http://www.gnu.org/software/emacs/manual/html_node/emacs/Grep-Searching.html )

**Comment by proofit404** [comment]
I will take a look on this issue after I implement `tramp` branch. I guess this will take significant amount of time.

Also you can try to implement it yourself but remember all contributions must be covered with tests.

**Comment by vskr** [comment]
Great! If you could break this task into smaller sub-tasks, would love to help. Would be great to learn elisp

**Comment by proofit404** [comment]
First of all I suggest you to learn concept of lexical bindings and lambda functions. Anaconda mode use this mechanics a lot because of its asynchronous nature. Also learn basics of `ert` library to write code covered with tests. If you will stuck at any point feel free to ping me here or directly via email. I will try to clarify this topic for you.

Good luck.

**Comment by proofit404** [comment]
Done.
