### ISSUE TITLE
"No definitions found" behaviour changed

### ISSUE THREAD

**Issue by NightBlues** [proofit404/anaconda-mode#147]
I used following advices to fall back to tags if anaconda couldn't find definition:
```
(defun fail-goto-definition (oldfunc &rest r)
  (condition-case nil
      (apply oldfunc r)
    (error (apply #'find-tag (find-tag-interactive "Find tag: ")))))
(advice-add 'anaconda-mode-goto :around #'fail-goto-definition)

(defun fail-pop-mark (oldfunc &rest r)
  (condition-case nil
      (apply oldfunc r)
    (error (pop-tag-mark))))
(advice-add 'anaconda-nav-pop-marker :around #'fail-pop-mark)
```
But after update it has been broken because anaconda-mode-goto (called anaconda-mode-find-definitions now) doesn't throw an error any more. How should i determine if no definitions found?

Thanks)

**Comment by proofit404** [comment]
You can't advice [anaconda-mode-find-definitions](https://github.com/proofit404/anaconda-mode/blob/ebd48263967f7f59f80444ea73e871f22b7ebebb/anaconda-mode.el#L432-L436) because this function start asynchronous communication and process definitions in the response callback. You can customize [anaconda-mode-find-definitions-callback](https://github.com/proofit404/anaconda-mode/blob/ebd48263967f7f59f80444ea73e871f22b7ebebb/anaconda-mode.el#L62-L66) variable and write your own callback which will trigger `find-tag` command:

```lisp
(defun fail-goto-callback (result)
  (if result
      (anaconda-mode-find-definitions-callback result)
    (apply #'find-tag (find-tag-interactive "Find tag: "))))

(setq anaconda-mode-find-definitions-callback #'fail-goto-callback)
```
Hope this help you. Good luck.

**Comment by NightBlues** [comment]
Thank you very match, it was so easy)
