### ISSUE TITLE
anaconda-mode jump-to-definition does not work for @classmethod

### ISSUE THREAD

**Issue by binbincong** [proofit404/anaconda-mode#205]
With anaconda-mode in spacemacs, I tried to use jump-to-definition or anaconda-mode-find-definitions for  test1 function with below code, and I got "Can't open __builtin__ module".

@classmethod
def test1(cls, arg1)
    pass

@classmethod
def test2(cls)
    cls.test1()

And after I removed @classmethod and changed to below code, it can work.

def test1(self, arg1)
    pass

def test2(self)
    self.test1()

**Comment by binbincong** [comment]
Detailed discussion can refer to the discussion in spacemacs repo https://github.com/syl20bnr/spacemacs/issues/7435

**Comment by proofit404** [comment]
Hi. This is totally expected behavior. If you call go to definition on something, it search for exact value of the name. In case of classmethod decorated functions it is classmethod descriptor (result of classmethod decorator application) written is C. We found where it was defined, but we can't navigate there. If you call go to assignments, it search the most recent usage of name. It can be anything defining a name: assignment expression, import statement, `as` keyword, etc. I this case we found decorator application, and happily shows it. Hope this make sense.
