### ISSUE TITLE
Some problems with decorated objects

### ISSUE THREAD

**Issue by cryptomaniac512** [proofit404/anaconda-mode#214]
Hi!

when I decorate some method/class/function I have some problems:

* eldoc can not show it correctly. It looks like
```_method(*args, **kwargs)```
instead of my function/method arguments

* anaconda-mode-goto-definition can not go to function/class/method declaration. It show me buffer with decorator or `Can't open __builtin__ module` if I use `@classmethod` or other builtins. But `anaconda-mode-find-assignments` works well.

Sorry for my bad english

**Comment by proofit404** [comment]
Hi, thanks for using my project!

Please read the answer to similar issue https://github.com/proofit404/anaconda-mode/issues/205#issuecomment-254186685

**Comment by cryptomaniac512** [comment]
Ok, but what about eldoc? Showing decorator arguments is correct behavior?

**Comment by proofit404** [comment]
Eldoc uses definitions search under the hood. In most cases this is what user expects to see. You can try to play with `anaconda_mode.py` sources. If you come with better solution, we can discus this further.

**Comment by gdevanla** [comment]
I am curious about this behavior. I have both anaconda-mode and jedi installed with emacs. While trying to jump to a definition using anaconda-find-definitions, I get 'Can't open builtinds module'. But, when I do the same use jedi:goto-definition, I am able to go to the definition.  Since, anaconda uses jedi in the backend, I am confused by the difference in behavior.  I tested this behaviour for a classmethod.

**Comment by proofit404** [comment]
`anaconda-mode` use jedi python library under the hood. Not the `jedi.el` Emacs package. `jedi.el` is alternative elisp wrapper so behavior can be different. I guess it tried to failback to assignment search when definitions search get no results.

**Comment by gdevanla** [comment]
OK. Thanks for clarifying. I will try to compare both the wrappers.
