### ISSUE TITLE
Add a CONTRIBUTING page

### ISSUE THREAD

**Issue by wizmer** [proofit404/anaconda-mode#245]
Hi, 

First, thanks for maintaining this awesome and critical project for Emacs python devs.
I'd like to dig into some issues I am having with anaconda and hopefully do a PR.
However I have no idea where to start with. I think having a dedicated CONTRIBUTING file or wiki page to get started with development would encourage newcomers to contribute to the project. For exemple, I am seeing exceptions in the *anaconda-mode* buffer but I have no idea how to investigate what's going on in the backend process. Describing the anaconda workflow would certainly help. 

Cheers

**Comment by proofit404** [comment]
Hi,

Thanks for reaching out.

I guess contributing file is excellent candidate for your first PR :)

High-level quick overview of anaconda-mode to start with it:

1. Anaconda-mode is written using lots of callback functions. This is because of asynchronous nature of network and process interactions.
2. When you pres `M-.`, anaconda-mode check if there is a started server with up to date environment settings.
3. If there is not such server, we will start a new one passing definitions search operations as a callback to server ready function.
4. When message with bound server port occurs in the process output we perform actual rpc call.
5. Rpc call is also an asynchronous operation done over network.
6. When python server (which actually do all job for definitions search) respond with result we show results to user in the response callback.

Also we have lots of intermediate checks and support running python server on remote host over ssh.

Hope this helps.
