### ISSUE TITLE
Please make anaconda-mode work on Emacs 25 again

### ISSUE THREAD

**Issue by bmag** [proofit404/anaconda-mode#298]
Hey @proofit404, what's the rationale for demanding [Emacs 26 as a hard requirement](https://github.com/proofit404/anaconda-mode/commit/3c63f68c5808a6323fc30809c89a3cf2dd6a0707) for anaconda-mode? As it is now, anaconda-mode *cannot even be installed from MELPA* for anyone who uses an older Emacs, and that presents a problem for all our Spacemacs users who didn't upgrade their Emacs version. Would it be possible to lower the requirement to Emacs 25.1?

I'm aware we could use an older version of anaconda-mode (say 0.1.11), but even in another half a year I'd still think it's reasonable to expect many users to still be on Emacs 25, so sticking to an old version of anaconda-mode long-term is something I'd like to avoid.

Obviously this problem also affects non-Spacemacs users of anaconda-mode, and I expect many of them to still be on an older Emacs version, which is very reasonable considering 26.1 was released just a week ago.

**Comment by proofit404** [comment]
Hi,

This is what I can offer.

* I relax the requirement to emacs 25.
* I will not work on issues if older emacs version will break
* If someone decides to fix it, in this case, I'll accept PR for backward compatibility.

This decision was made because of my lack of time to work on the package.

Regards, Artem.

**Comment by bmag** [comment]
Ok, thank you very much.
