### ISSUE TITLE
Support optional parameter to open other window in anacanda-mode-goto

### ISSUE THREAD

**Issue by semente** [proofit404/anaconda-mode#61]
When I do `M-.` it open the new buffer or position in the same window. Would be great if with `C-u M-.` it open the new buffer in the other window, like in `find-file-other-window`

**Comment by proofit404** [comment]
Actually I doesn't like current go to definition behaviour. In the earlyer version anaconda mode mimic etags commands behaviour. But use with completion-read function annoing many users. I'll rewrite it in more productive way soon. So `anaconda-mode-goto-defenition-other-window` and `anaconda-mode-goto-defenition-other-frame` commands will come back. Please, wait for a while.

Regards, Artem.

**Comment by semente** [comment]
Great! I appreciate it.

**Comment by proofit404** [comment]
Resent `anaconda-mode` try to be more or less `*grep*`-like for multiple definitions/references.

Can we elaborate on optimal behavior of navigation commands? It's clear to me what to do in the case of single definition. We can add other window/frame commands easily for this case.

But what is the right behavior for multiple definitions case.

**Comment by cpaulik** [comment]
I would also really appreciate the `other-window/frame` functions. In case of multiple definitions why not use the completion framework to show a list to the user. From the completion framework the user should be able to decide if they want to open it in a new frame. At least this is possible in helm with `C-c o` but I don't know about `ivy` or stock emacs.

**Comment by proofit404** [comment]
Completion framework usage is the goal for additional packages like `helm-anaconda`. Do you have any ideas for open in other frame/window functions with multiple candidates without external completion framework? We can't use xref as the only option because older emacs versions are officially supported.

**Comment by cpaulik** [comment]
Why not do the same as with find references if there are multiple definitions? Show a buffer with a list and then let the user choose. This list buffer could then behave differently if it was called by the normal 
`anaconda-mode-find-definitions` or by the `other-frame/window` version.

I've never had the case of multiple definitions, how can that happen? I just want to know so that I can test it.

**Comment by proofit404** [comment]
Different platform specific implementation injected at runtime, for example.

**Comment by dakra** [comment]
Friendly bump and just another vote for `anaconda-mode-find-definitions-other-frame`.

**Comment by proofit404** [comment]
I don't mind to implement it. It's straightforward how to do it with only one definition. But I can't imagine what kind of UI we need for multiple definitions.

**Comment by dakra** [comment]
Just open the `*Anaconda*` grep like buffer like normal and if you
select an item in there it'll change 'other-frame/window' instead
of the current when called with prefix argument.

Or even if the 'other-frame' behavior is not implemented
for multiple definitions and falls back to what it is now,
I wouldn't mind very much since imho 95% of the time you
only have one definition.

BTW, love anaconda-mode, great package :+1:

**Comment by c02y** [comment]
Is this feature not implemented yet? It is now 2018.

**Comment by proofit404** [comment]
It's my side project, I work on features I use myself when I'm in the right mood. I don't care what year it is, because this project does not have a roadmap and never will.

**Comment by c02y** [comment]
@proofit404 OK! Do you accept such pull-request?

**Comment by proofit404** [comment]
If it's implemented properly and don't break anything, of course I do.

**Comment by proofit404** [comment]
Done.
